sudo: required
language: ruby
rvm:
- 2.2.1
deploy:
  provider: heroku
  api_key:
    secure: FZYcqxvpzoEpjXPQlGW2ItTndFS/VjYFuuZTBq0NN3ZrvyCTQZeqpHIMlfinT9LsZyfnIbG6HvNepU/te3DVTaLZc+YVfUsGIY/hAByYWtqiuv9iHmDrKTlkNgGl3QooDuG5CLp99nCZtXK+4T1Xy4WOyv2Ff2mRCExRF4YAeQe/xJtAhm1TDirWOFef/E7YJEeipIylLq8bwyiw6FonXUwobxrcQWMSYzpwXJQ2pyzeOys/6TZZvjSAMlt6Vw1id3gdzo/8XAg6rmXfI6DnULPFLl090oatVqsYiikg5Lh6bNtGxHxn7NRYgmSOd17un9vuTsrXHosFihB0vkkBSdUumghUvPcJUmqbtGTdAJQ9io1zx1c8KPS70iA0LhuIEIEQZ0PXa0ts+MyNSfX3mF5er+kWP4B+Y8kB0yrlMKRFfAHYYlmyVpy4n2HKGxNg+E/B3ZVqzFzlvlx8wYAhoEaEc8dL8t8TyK7Kt2XocH4gojN7FBXGRubEQIU7H3TO3mTjtDE+lsz9r0EbPuHJ05wqdqkY8pku3nCuC9M3S7rOA+N3YdKnBciWWhQmTmKT0Xz1yPt+c+RPW5VhTEslKcvnzvTfxJGL3sjk/YfII+iB4TobXZpXZd/ySqAx/5kJsKZgfK2/mNOOEDgnjkqTAfy5MWbNt+uJSYDhN09ixp0=
  app: serene-waters-38928

